In [1]:
#importing the Libraies numpy, matplotlib and pandas
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
#Use the pandas library funtion read the csv data file and store it in the dataset variable
dataset=pd.read_csv("insurance_pre.csv")

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
#Using the get_dummies function, we convert a categorical (nominal) column like “smoke into multiple separate columns. This process is called one-hot encoding.
# True=1 and false=0
dataset=pd.get_dummies(dataset,drop_first=True) # remove the dummy column.Here remove the sex_female,Smoker_no
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [5]:
# show the column name
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [6]:
#input - In the dataset column value and store it the independent variable. Only input heading value put here
indep=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
indep

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0     False        True
1      18  33.770         1      True       False
2      28  33.000         3      True       False
3      33  22.705         0      True       False
4      32  28.880         0      True       False
...   ...     ...       ...       ...         ...
1333   50  30.970         3      True       False
1334   18  31.920         0     False       False
1335   18  36.850         0     False       False
1336   21  25.800         0     False       False
1337   61  29.070         0     False        True

[1338 rows x 5 columns]

In [8]:
#output - In the dataset column value and store it the dependent variable. Only output heading value put here
dep=dataset['charges']
dep

0       16884.92400
1        1725.55230
2        4449.46200
3       21984.47061
4        3866.85520
           ...
1333    10600.54830
1334     2205.98080
1335     1629.83350
1336     2007.94500
1337    29141.36030
Name: charges, Length: 1338, dtype: float64

In [22]:
#split into training set and test
#from sklearn.model_selection import train_test_split
#X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [23]:
# Here we can used standardisation in sklearn library and import StandardScalar fumction
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [24]:
#x_train value
X_train

array([[-1.53963418,  0.11036616, -0.90788827, -0.98885138, -0.49929923],
       [ 0.74809711,  0.26412451, -0.0755796 ,  1.01127431,  2.00280702],
       [ 0.4621307 ,  2.13997636,  1.58903774,  1.01127431, -0.49929923],
       ...,
       [ 0.03318108, -0.90443894, -0.90788827,  1.01127431, -0.49929923],
       [-1.46814257,  0.7869029 , -0.90788827,  1.01127431, -0.49929923],
       [-0.46726014, -1.96941782, -0.0755796 , -0.98885138, -0.49929923]],
      shape=(892, 5))

In [25]:
#using sklearn library and import SVM function in SVR variable, model selection in Grid search
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
param_grid={'kernel':['rbf','poly','sigmoid','linear'],'C':[10,100,1000,2000,3000],'gamma':['auto','scale']}
grid = GridSearchCV(SVR(),param_grid,refit = True, verbose = 3, n_jobs=-1)
# fitting the model for grid search
grid.fit(X_train, y_train)

Fitting 5 folds for each of 40 candidates, totalling 200 fits

GridSearchCV(estimator=SVR(), n_jobs=-1,
             param_grid={'C': [10, 100, 1000, 2000, 3000],
                         'gamma': ['auto', 'scale'],
                         'kernel': ['rbf', 'poly', 'sigmoid', 'linear']},
             verbose=3)

In [26]:
# print best parameter after tuning
#print(grid.best_params_)
re=grid.cv_results_
print("The R_score value for best parameter {}:".format(grid.best_params_))

The R_score value for best parameter {'C': 3000, 'gamma': 'scale', 'kernel': 'poly'}:

In [27]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.082392,0.012090,0.032348,0.004241,10,auto,rbf,"{'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}",-0.004176,0.022594,-0.118956,-0.082926,-0.103473,-0.057387,0.056205,35
1,0.051815,0.009435,0.011673,0.002385,10,auto,poly,"{'C': 10, 'gamma': 'auto', 'kernel': 'poly'}",0.047420,0.077536,-0.060527,-0.009476,-0.050823,0.000826,0.054025,32
2,0.092401,0.005312,0.019526,0.002815,10,auto,sigmoid,"{'C': 10, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.044787,0.081689,-0.072355,-0.027541,-0.051470,-0.004978,0.058648,34
3,0.052749,0.002586,0.009936,0.000854,10,auto,linear,"{'C': 10, 'gamma': 'auto', 'kernel': 'linear'}",0.387624,0.461268,0.288301,0.340540,0.297825,0.355112,0.063693,25
4,0.089904,0.002046,0.035539,0.002528,10,scale,rbf,"{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}",-0.003956,0.022453,-0.119035,-0.082925,-0.103510,-0.057395,0.056230,36
5,0.061957,0.003456,0.011673,0.001581,10,scale,poly,"{'C': 10, 'gamma': 'scale', 'kernel': 'poly'}",0.043648,0.079780,-0.059229,-0.009498,-0.050317,0.000877,0.053658,31
6,0.097643,0.004677,0.020562,0.001135,10,scale,sigmoid,"{'C': 10, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.043946,0.082230,-0.072132,-0.027546,-0.051337,-0.004968,0.058595,33
7,0.060312,0.002447,0.012738,0.002038,10,scale,linear,"{'C': 10, 'gamma': 'scale', 'kernel': 'linear'}",0.387624,0.461268,0.288301,0.340540,0.297825,0.355112,0.063693,25
8,0.092945,0.002968,0.034283,0.002706,100,auto,rbf,"{'C': 100, 'gamma': 'auto', 'kernel': 'rbf'}",0.303414,0.319385,0.155546,0.208414,0.161756,0.229703,0.069348,29
9,0.066828,0.005539,0.012082,0.001008,100,auto,poly,"{'C': 100, 'gamma': 'auto', 'kernel': 'poly'}",0.542212,0.566743,0.471172,0.537557,0.413719,0.506281,0.056081,22
10,0.094648,0.003268,0.018525,0.001209,100,auto,sigmoid,"{'C': 100, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.492088,0.545107,0.438714,0.468576,0.425516,0.474000,0.042447,23
11,0.066830,0.006652,0.010685,0.000893,100,auto,linear,"{'C': 100, 'gamma': 'auto', 'kernel': 'linear'}",0.596232,0.635776,0.566816,0.588799,0.537415,0.585008,0.032600,19
12,0.091677,0.003442,0.034312,0.003096,100,scale,rbf,"{'C': 100, 'gamma': 'scale', 'kernel': 'rbf'}",0.304939,0.318480,0.155033,0.208422,0.161488,0.229672,0.069604,30
13,0.068522,0.003240,0.010462,0.002834,100,scale,poly,"{'C': 100, 'gamma': 'scale', 'kernel': 'poly'}",0.532310,0.571466,0.474948,0.537506,0.415264,0.506299,0.055077,21
14,0.096385,0.004567,0.018944,0.001766,100,scale,sigmoid,"{'C': 100, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.491855,0.544604,0.439299,0.468556,0.424226,0.473708,0.042461,24
15,0.071712,0.009309,0.011746,0.002795,100,scale,linear,"{'C': 100, 'gamma': 'scale', 'kernel': 'linear'}",0.596232,0.635776,0.566816,0.588799,0.537415,0.585008,0.032600,19
16,0.111696,0.003068,0.038731,0.002692,1000,auto,rbf,"{'C': 1000, 'gamma': 'auto', 'kernel': 'rbf'}",0.731430,0.716349,0.686476,0.710172,0.613293,0.691544,0.041718,11
17,0.097219,0.006212,0.011656,0.002342,1000,auto,poly,"{'C': 1000, 'gamma': 'auto', 'kernel': 'poly'}",0.799185,0.786769,0.821307,0.810704,0.719528,0.787499,0.035885,8
18,0.110624,0.004940,0.019349,0.000433,1000,auto,sigmoid,"{'C': 1000, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.232428,0.306815,0.236688,0.291707,0.346868,0.282901,0.043415,28
19,0.090850,0.002337,0.011221,0.000865,1000,auto,linear,"{'C': 1000, 'gamma': 'auto', 'kernel': 'linear'}",0.686126,0.598398,0.586104,0.573860,0.556109,0.600119,0.045217,13
20,0.115712,0.004143,0.036744,0.000941,1000,scale,rbf,"{'C': 1000, 'gamma': 'scale', 'kernel': 'rbf'}",0.732079,0.715992,0.686057,0.710177,0.613122,0.691485,0.041876,12
21,0.093770,0.003806,0.013276,0.000549,1000,scale,poly,"{'C': 1000, 'gamma': 'scale', 'kernel': 'poly'}",0.798212,0.787019,0.823118,0.810712,0.719979,0.787808,0.036003,7
22,0.102480,0.003398,0.022143,0.000980,1000,scale,sigmoid,"{'C': 1000, 'gamma': 'scale', 'kernel': 'sigmo...",0.248266,0.377692,0.315321,0.291779,0.346175,0.315846,0.044478,27
23,0.092000,0.006838,0.010065,0.000831,1000,scale,linear,"{'C': 1000, 'gamma': 'scale', 'kernel': 'linear'}",0.686126,0.598398,0.586104,0.573860,0.556109,0.600119,0.045217,13
24,0.119154,0.005003,0.038854,0.003569,2000,auto,rbf,"{'C': 2000, 'gamma': 'auto', 'kernel': 'rbf'}",0.788746,0.764261,0.818616,0.794131,0.709676,0.775086,0.036986,9
25,0.202970,0.082091,0.013024,0.000671,2000,auto,poly,"{'C': 2000, 'gamma': 'auto', 'kernel': 'poly'}",0.804603,0.784782,0.847674,0.807280,0.745448,0.797957,0.033268,4
26,0.105859,0.007334,0.018962,0.001795,2000,auto,sigmoid,"{'C': 2000, 'gamma': 'auto', 'kernel': 'sigmoid'}",-0.656854,-0.432695,-0.346330,-0.484052,-0.076409,-0.399268,0.190629,38
27,0.115751,0.012746,0.011664,0.000893,2000,auto,linear,"{'C': 2000, 'gamma': 'auto', 'kernel': 'linear'}",0.669958,0.592446,0.586953,0.572862,0.556109,0.595666,0.039218,15
28,0.120098,0.006109,0.033676,0.001394,2000,scale,rbf,"{'C': 2000, 'gamma': 'scale', 'kernel': 'rbf'}",0.789144,0.764022,0.818319,0.794133,0.709586,0.775041,0.036992,10
29,0.233514,0.199615,0.011908,0.002299,2000,scale,poly,"{'C': 2000, 'gamma': 'scale', 'kernel': 'poly'}",0.804708,0.784713,0.847781,0.807295,0.745732,0.798046,0.033220,3
30,0.109346,0.007087,0.019547,0.002268,2000,scale,sigmoid,"{'C': 2000, 'gamma': 'scale', 'kernel': 'sigmo...",-0.370980,-0.421011,-0.350248,-0.483750,-0.087414,-0.342681,0.135687,37
31,0.121033,0.012200,0.010966,0.000734,2000,scale,linear,"{'C': 2000, 'gamma': 'scale', 'kernel': 'linear'}",0.669958,0.592446,0.586953,0.572862,0.556109,0.595666,0.039218,15
32,0.137361,0.006459,0.034805,0.002145,3000,auto,rbf,"{'C': 3000, 'gamma': 'auto', 'kernel': 'rbf'}",0.795104,0.772917,0.846181,0.811601,0.725697,0.790300,0.040188,5
33,0.376824,0.251655,0.011633,0.002319,3000,auto,poly,"{'C': 3000, 'gamma': 'auto', 'kernel': 'poly'}",0.804915,0.783304,0.852190,0.810160,0.748175,0.799749,0.034104,2
34,0.114036,0.006356,0.020639,0.001030,3000,auto,sigmoid,"{'C': 3000, 'gamma': 'auto', 'kernel': 'sigmoid'}",-1.795299,-1.629662,-1.461919,-1.712710,-0.929359,-1.505790,0.308601,39
35,0.147639,0.020769,0.009868,0.001677,3000,auto,linear,"{'C': 3000, 'gamma': 'auto', 'kernel': 'linear'}",0.669819,0.588893,0.587076,0.572849,0.557014,0.595130,0.039068,17
36,0.133188,0.003901,0.034516,0.004123,3000,scale,rbf,"{'C': 3000, 'gamma': 'scale', 'kernel': 'rbf'}",0.795353,0.772801,0.846034,0.811601,0.725615,0.790281,0.040189,6
37,0.204015,0.050828,0.010490,0.002270,3000,scale,poly,"{'C': 3000, 'gamma': 'scale', 'kernel': 'poly'}",0.805169,0.783163,0.852345,0.810160,0.748201,0.799808,0.034165,1
38,0.113141,0.004193,0.019061,0.001393,3000,scale,sigmoid,"{'C': 3000, 'gamma': 'scale', 'kernel': 'sigmo...",-1.651895,-2.010670,-1.468842,-1.712109,-0.961821,-1.561068,0.346643,40
39,0.103900,0.017021,0.007142,0.000546,3000,scale,linear,"{'C': 3000, 'gamma': 'scale', 'kernel': 'linear'}",0.669819,0.588893,0.587076,0.572849,0.557014,0.595130,0.039068,17

In [28]:
#Run time input
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age: 32
BMI: 43
Children: 2
Sex Male 0 or 1: 0
Smoker Yes 0 or 1: 1

In [29]:
#Run time prediction output
Future_Prediction = grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print('Future Prediction={}'.format(Future_Prediction))

Future Prediction=[3316415.7200446]