In [1]:
#importing the Libraies numpy, matplotlib and pandas
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
#Use the pandas library funtion read the csv data file and store it in the dataset variable
dataset=pd.read_csv("insurance_pre.csv")

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
#Using the get_dummies function, we convert a categorical (nominal) column like “smoke into multiple separate columns. This process is called one-hot encoding.
# True=1 and false=0
dataset=pd.get_dummies(dataset,drop_first=True) # remove the dummy column.Here remove the sex_female,Smoker_no
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [5]:
# show the column name
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [6]:
#input - In the dataset column value and store it the independent variable. Only input heading value put here
indep=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
indep

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0     False        True
1      18  33.770         1      True       False
2      28  33.000         3      True       False
3      33  22.705         0      True       False
4      32  28.880         0      True       False
...   ...     ...       ...       ...         ...
1333   50  30.970         3      True       False
1334   18  31.920         0     False       False
1335   18  36.850         0     False       False
1336   21  25.800         0     False       False
1337   61  29.070         0     False        True

[1338 rows x 5 columns]

In [7]:
#output - In the dataset column value and store it the dependent variable. Only output heading value put here
dep=dataset['charges']
dep

0       16884.92400
1        1725.55230
2        4449.46200
3       21984.47061
4        3866.85520
           ...
1333    10600.54830
1334     2205.98080
1335     1629.83350
1336     2007.94500
1337    29141.36030
Name: charges, Length: 1338, dtype: float64

In [17]:
#split into training set and test
#from sklearn.model_selection import train_test_split
#X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [18]:
# Here we can used standardisation in sklearn library and import StandardScalar fumction
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [19]:
#x_train value
X_train

array([[-1.53963418,  0.11036616, -0.90788827, -0.98885138, -0.49929923],
       [ 0.74809711,  0.26412451, -0.0755796 ,  1.01127431,  2.00280702],
       [ 0.4621307 ,  2.13997636,  1.58903774,  1.01127431, -0.49929923],
       ...,
       [ 0.03318108, -0.90443894, -0.90788827,  1.01127431, -0.49929923],
       [-1.46814257,  0.7869029 , -0.90788827,  1.01127431, -0.49929923],
       [-0.46726014, -1.96941782, -0.0755796 , -0.98885138, -0.49929923]],
      shape=(892, 5))

In [20]:
#using using sklearn library and random forest regressor, model selection in Grid search
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor
param_grid = {'criterion':['squared_error','absolute_error','friedman_mse','poisson'],
'max_features': ['auto','sqrt','log2'],
'n_estimators':[10,100]}
grid = GridSearchCV(RandomForestRegressor(), param_grid, refit = True, verbose = 3,n_jobs=-1)
# fitting the model for grid search
grid.fit(X_train, y_train)

Fitting 5 folds for each of 24 candidates, totalling 120 fits

C:\Users\Mani\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:516: FitFailedWarning:
40 fits failed out of a total of 120.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
16 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Mani\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mani\anaconda3\Lib\site-packages\sklearn\base.py", line 1358, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Mani\anaconda3\Lib\site-packages\sklearn\base.py", line 471, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Mani\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

--------------------------------------------------------------------------------
24 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Mani\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mani\anaconda3\Lib\site-packages\sklearn\base.py", line 1358, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Mani\anaconda3\Lib\site-packages\sklearn\base.py", line 471, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Mani\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\Mani\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:1135: UserWarning: One or more of the test scores are non-finite: [       nan        nan 0.77849646 0.80370484 0.78312961 0.79968224
        nan        nan 0.78424727 0.80269817 0.78366233 0.8009586
        nan        nan 0.78029748 0.80042958 0.78041747 0.80153729
        nan        nan 0.77819146 0.79977552 0.78320154 0.80290836]
  warnings.warn(

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'absolute_error',
                                       'friedman_mse', 'poisson'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             verbose=3)

In [13]:
# print best parameter after tuning
#print(grid.best_params_)
re=grid.cv_results_
#print(re)
grid_predictions = grid.predict(X_test)
# print classification report
from sklearn.metrics import r2_score
r_score=r2_score(y_test,grid_predictions)
print("The R_score value for best parameter {}:".format(grid.best_params_),r_score)

The R_score value for best parameter {'criterion': 'friedman_mse', 'max_features': 'sqrt', 'n_estimators': 100}: 0.8745946256664718

In [14]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002445,0.000810,0.000000,0.000000,squared_error,auto,10,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
1,0.003627,0.001304,0.000000,0.000000,squared_error,auto,100,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
2,0.074248,0.009158,0.009397,0.001369,squared_error,sqrt,10,"{'criterion': 'squared_error', 'max_features':...",0.797357,0.734606,0.819912,0.789030,0.748613,0.777904,0.031621,13
3,0.633915,0.008578,0.034104,0.001896,squared_error,sqrt,100,"{'criterion': 'squared_error', 'max_features':...",0.807303,0.771873,0.840060,0.825552,0.758782,0.800714,0.030979,4
4,0.073869,0.002727,0.008199,0.001951,squared_error,log2,10,"{'criterion': 'squared_error', 'max_features':...",0.770338,0.755358,0.819005,0.806931,0.746785,0.779684,0.028460,12
5,0.610029,0.007106,0.032130,0.002543,squared_error,log2,100,"{'criterion': 'squared_error', 'max_features':...",0.802145,0.773833,0.837343,0.822386,0.756301,0.798402,0.029939,7
6,0.002460,0.000739,0.000000,0.000000,absolute_error,auto,10,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
7,0.001333,0.000098,0.000000,0.000000,absolute_error,auto,100,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
8,0.166705,0.004728,0.007256,0.001041,absolute_error,sqrt,10,"{'criterion': 'absolute_error', 'max_features'...",0.786578,0.754721,0.817712,0.820270,0.737663,0.783389,0.033049,10
9,1.603189,0.020855,0.032415,0.002307,absolute_error,sqrt,100,"{'criterion': 'absolute_error', 'max_features'...",0.800166,0.775424,0.846704,0.828390,0.767364,0.803610,0.030303,3
10,0.163767,0.007238,0.006417,0.000611,absolute_error,log2,10,"{'criterion': 'absolute_error', 'max_features'...",0.794090,0.740689,0.816493,0.779573,0.750875,0.776344,0.027775,15
11,1.589698,0.016175,0.027282,0.001912,absolute_error,log2,100,"{'criterion': 'absolute_error', 'max_features'...",0.788199,0.764447,0.839624,0.817697,0.758940,0.793781,0.030916,8
12,0.001822,0.000674,0.000000,0.000000,friedman_mse,auto,10,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
13,0.001701,0.000639,0.000000,0.000000,friedman_mse,auto,100,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
14,0.061368,0.002324,0.006318,0.000359,friedman_mse,sqrt,10,"{'criterion': 'friedman_mse', 'max_features': ...",0.791177,0.752622,0.811712,0.800579,0.750682,0.781355,0.025116,11
15,0.573440,0.008680,0.031703,0.003306,friedman_mse,sqrt,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.811734,0.769251,0.838895,0.836188,0.765318,0.804277,0.031676,1
16,0.063322,0.001946,0.006320,0.000142,friedman_mse,log2,10,"{'criterion': 'friedman_mse', 'max_features': ...",0.784613,0.751493,0.830613,0.799837,0.756694,0.784650,0.029066,9
17,0.541863,0.012342,0.031255,0.002156,friedman_mse,log2,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.811105,0.761431,0.830919,0.833122,0.760565,0.799428,0.032303,6
18,0.001973,0.000631,0.000000,0.000000,poisson,auto,10,"{'criterion': 'poisson', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
19,0.001996,0.000946,0.000000,0.000000,poisson,auto,100,"{'criterion': 'poisson', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
20,0.063345,0.004068,0.005175,0.001660,poisson,sqrt,10,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.763256,0.745010,0.818033,0.818305,0.734660,0.775853,0.035744,16
21,0.568468,0.014208,0.022096,0.001479,poisson,sqrt,100,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.806394,0.765890,0.840205,0.832551,0.756635,0.800335,0.033942,5
22,0.062863,0.002343,0.005423,0.001338,poisson,log2,10,"{'criterion': 'poisson', 'max_features': 'log2...",0.786555,0.727906,0.819155,0.811052,0.742874,0.777508,0.036336,14
23,0.434168,0.021090,0.017096,0.001591,poisson,log2,100,"{'criterion': 'poisson', 'max_features': 'log2...",0.811646,0.779440,0.839037,0.830301,0.759892,0.804063,0.030088,2

In [21]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age: 22
BMI: 60
Children: 2
Sex Male 0 or 1: 0
Smoker Yes 0 or 1: 1

In [22]:
#Run time prediction output
Future_Prediction = grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print('Future Prediction={}'.format(Future_Prediction))

Future Prediction=[47767.6836443]