In [1]:
#importing the Libraies from pandas, matplotlib & numpy
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
#Use the pandas library funtion read the csv data file and store it in the dataset variable
dataset=pd.read_csv("Social_Network_Ads.csv")

In [3]:
dataset

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [4]:
#Using the get_dummies function, we convert a categorical (nominal) column like “Gender" into multiple separate columns. This process is called one-hot encoding.
# True=1 and false=0
dataset = pd.get_dummies(dataset,dtype=int,drop_first=True) # remove the dummy column.Here remove the Gender_female
dataset

      User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [5]:
# dataset Purchased column value count 0 is not purchased, 1 is purchased, based on this value will take a balance or imbalance data
dataset["Purchased"].value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

In [6]:
#input - In the dataset column value and store it the independent variable. Only input heading value put here
indep=dataset[["Age","EstimatedSalary","Gender_Male"]]
#output - In the dataset column value and store it the dependent variable. Only output heading value put here
dep=dataset["Purchased"]

In [7]:
indep.shape

(400, 3)

In [8]:
dep

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [9]:
#Split training and test set using sklearn library and import only train_test_split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(indep,dep,test_size=0.30,random_state=0)

In [10]:
#using sklearn library and import KN Neighbour function
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=7, metric = 'minkowski', p=2)
classifier = classifier.fit(X_train,y_train) # This code will create model

In [11]:
#Evaluation metrics - process of prediction
y_pred = classifier.predict(X_test)

In [12]:
#Calculate the Confusion matrix value and weather check the model is good or bad.
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [13]:
print(cm)

[[72  7]
 [13 28]]

In [14]:
#classification report - depends on confusion matrix
from sklearn.metrics import classification_report
clf_report = classification_report(y_test,y_pred)

In [15]:
print(clf_report)

              precision    recall  f1-score   support

           0       0.85      0.91      0.88        79
           1       0.80      0.68      0.74        41

    accuracy                           0.83       120
   macro avg       0.82      0.80      0.81       120
weighted avg       0.83      0.83      0.83       120