In [1]:
#importing the Libraies from pandas, matplotlib & numpy
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
#Use the pandas library funtion read the csv data file and store it in the dataset variable
dataset=pd.read_csv("Social_Network_Ads.csv")

In [3]:
dataset

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [4]:
#Using the get_dummies function, we convert a categorical (nominal) column like “Gender" into multiple separate columns. This process is called one-hot encoding.
# True=1 and false=0
dataset = pd.get_dummies(dataset,dtype=int,drop_first=True) # remove the dummy column.Here remove the Gender_female
dataset

      User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [5]:
# dataset Purchased column value count 0 is not purchased, 1 is purchased, based on this value will take a balance or imbalance data
dataset["Purchased"].value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

In [6]:
#input - In the dataset column value and store it the independent variable. Only input heading value put here
indep=dataset[["Age","EstimatedSalary","Gender_Male"]]
#output - In the dataset column value and store it the dependent variable. Only output heading value put here
dep=dataset["Purchased"]

In [7]:
indep.shape

(400, 3)

In [8]:
dep

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [9]:
#Split training and test set using sklearn library and import only train_test_split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(indep,dep,test_size=0.30,random_state=0)

In [10]:
#using sklearn library and import Gaussian naivee bayee function
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier = classifier.fit(X_train,y_train) # This code will create model
y_pred = classifier.predict(X_test) #Evaluation metrics - process of prediction
#Calculate the Confusion matrix value and weather check the model is good or bad.
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
#classification report - depends on confusion matrix
from sklearn.metrics import classification_report
clf_report = classification_report(y_test,y_pred)
print("-----------CLF Report - Start----------")
print(clf_report)
print("-----------CLF Report - End----------")
print(cm)

-----------CLF Report - Start----------
              precision    recall  f1-score   support

           0       0.90      0.94      0.92        79
           1       0.87      0.80      0.84        41

    accuracy                           0.89       120
   macro avg       0.89      0.87      0.88       120
weighted avg       0.89      0.89      0.89       120

-----------CLF Report - End----------
[[74  5]
 [ 8 33]]

In [11]:
#using sklearn library and import Multinominal naivee bayee function
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB()
classifier = classifier.fit(X_train,y_train) # This code will create model
y_pred = classifier.predict(X_test) #Evaluation metrics - process of prediction
#Calculate the Confusion matrix value and weather check the model is good or bad.
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
#classification report - depends on confusion matrix
from sklearn.metrics import classification_report
clf_report = classification_report(y_test,y_pred)
print("-----------CLF Report - Start----------")
print(clf_report)
print("-----------CLF Report - End----------")
print(cm)

-----------CLF Report - Start----------
              precision    recall  f1-score   support

           0       0.71      0.86      0.78        79
           1       0.54      0.32      0.40        41

    accuracy                           0.68       120
   macro avg       0.62      0.59      0.59       120
weighted avg       0.65      0.68      0.65       120

-----------CLF Report - End----------
[[68 11]
 [28 13]]

In [12]:
#using sklearn library and import Bernoulli naivee bayee function
from sklearn.naive_bayes import BernoulliNB
classifier = BernoulliNB()
classifier = classifier.fit(X_train,y_train) # This code will create model
y_pred = classifier.predict(X_test) #Evaluation metrics - process of prediction
#Calculate the Confusion matrix value and weather check the model is good or bad.
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
#classification report - depends on confusion matrix
from sklearn.metrics import classification_report
clf_report = classification_report(y_test,y_pred)
print("-----------CLF Report - Start----------")
print(clf_report)
print("-----------CLF Report - End----------")
print(cm)

-----------CLF Report - Start----------
              precision    recall  f1-score   support

           0       0.66      1.00      0.79        79
           1       0.00      0.00      0.00        41

    accuracy                           0.66       120
   macro avg       0.33      0.50      0.40       120
weighted avg       0.43      0.66      0.52       120

-----------CLF Report - End----------
[[79  0]
 [41  0]]

C:\Users\Mani\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\Mani\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\Mani\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [13]:
#using sklearn library and import Categorical naivee bayee function
from sklearn.naive_bayes import CategoricalNB
classifier = CategoricalNB()
classifier = classifier.fit(X_train,y_train) # This code will create model
y_pred = classifier.predict(X_test) #Evaluation metrics - process of prediction
#Calculate the Confusion matrix value and weather check the model is good or bad.
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
#classification report - depends on confusion matrix
from sklearn.metrics import classification_report
clf_report = classification_report(y_test,y_pred)
print("-----------CLF Report - Start----------")
print(clf_report)
print("-----------CLF Report - End----------")
print(cm)

-----------CLF Report - Start----------
              precision    recall  f1-score   support

           0       0.89      0.96      0.93        79
           1       0.91      0.78      0.84        41

    accuracy                           0.90       120
   macro avg       0.90      0.87      0.88       120
weighted avg       0.90      0.90      0.90       120

-----------CLF Report - End----------
[[76  3]
 [ 9 32]]

In [15]:
#using sklearn library and import Complement naivee bayee function
from sklearn.naive_bayes import ComplementNB
classifier = ComplementNB()
classifier = classifier.fit(X_train,y_train) # This code will create model
y_pred = classifier.predict(X_test) #Evaluation metrics - process of prediction
#Calculate the Confusion matrix value and weather check the model is good or bad.
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
#classification report - depends on confusion matrix
from sklearn.metrics import classification_report
clf_report = classification_report(y_test,y_pred)
print("-----------CLF Report - Start----------")
print(clf_report)
print("-----------CLF Report - End----------")
print(cm)

-----------CLF Report - Start----------
              precision    recall  f1-score   support

           0       0.68      0.53      0.60        79
           1       0.36      0.51      0.42        41

    accuracy                           0.53       120
   macro avg       0.52      0.52      0.51       120
weighted avg       0.57      0.52      0.54       120

-----------CLF Report - End----------
[[42 37]
 [20 21]]